### ISSUE TITLE
martian rover imagery page

### ISSUE THREAD

**Issue by Chandu6702** [PranavBarthwal/cosmoXplore#225]
### Describe the feature

I will add a button with an event listener that can close the displayed content.to

### It should be implemented because

when we click on enter button in "Display on entering date section" rover info is displayed but we are unable to close it. we have to refresh the site to close.

### Additional context
![Screenshot 2024-05-23 113805](https://github.com/PranavBarthwal/cosmoXplore/assets/125206920/db751034-80a2-444e-8f42-23e402f5700a)

please assign this to me.

### Would you like to work on this issue?

Yes

**Comment by Chandu6702** [comment]
@surajvast1 please assign this to me

**Comment by Chandu6702** [comment]
@surajvast1 please assign this

**Comment by Chandu6702** [comment]
@PranavBarthwal please assign this to me

**Comment by Chandu6702** [comment]
@PranavBarthwal please assign this to me

**Comment by surajvast1** [comment]
Hi @Chandu6702,

We would like to move this content to a new page similar to the NASA projects page. Include a description of the content and ensure the APIs are set up correctly so that all the contents are visible. Additionally, Also add a closing button for better navigation.

Would you be willing to work on all this ?

**Comment by Chandu6702** [comment]
Hey @surajvast1 ,yeah sure I can work on this

**Comment by surajvast1** [comment]
Take it  @Chandu6702.
Thanks😃
